name: SAST Scan with SonarQube and DefectDojo

on:
  workflow_dispatch:

jobs:
  sast:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      #- name: Setup .NET
       # uses: actions/setup-dotnet@v3
        #with:
         # dotnet-version: '9.0.x'

      - name: Install SonarScanner for MSBuild
        run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:$HOME/.dotnet/tools"

      - name: Start SonarQube Scan
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet-sonarscanner begin /k:"my-csharp-app" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="http://localhost:9000"
          dotnet build
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Convert Sonar Report to SARIF (optional)
        run: |
          # Optional: Convert or extract SARIF if needed by DefectDojo
          echo "No-op if Sonar SARIF is not required"

      - name: Upload to DefectDojo
        run: |
          curl -k -X POST "http://localhost:8080/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -F "scan_type=SonarQube Scan" \
            -F "file=@path/to/report.zip" \
            -F "engagement=1" \
            -F "minimum_severity=Low" \
            -F "active=true" \
            -F "verified=true"
